PUT harp
PUT mnf

PUT mnf/investigator/_mapping
{
    "investigator": {
      "_timestamp": { 
        "enabled": true
      },
      "properties": { 
          "location": {
            "type": "geo_point",
            "geohash":     true,
            "geohash_precision":  "7" 
        },
        "Date/Time": {
            "type": "integer"
        }
        
      }
    }
}

PUT harp/temperature/_mapping
{
    "temperature": {
      "_timestamp": { 
        "enabled": true
      }
    }
}


POST harp/temperature/
{
    "value": 20.5
}

PUT harp/temperature/5/_create
{
    "value": 21.14
}

GET /mnf/investigator/_search
{
   "query": {
      "match_all": {}
      }
}

GET /mnf/investigator/

GET /mnf/investigator/_search
{
   "query": {
      "match_all": {}
      },
    "fields": {
        "_source": {},
    }
}
    
# delete all index
#DELETE /harp

DELETE /mnf/